name: golang-lint test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Run golang-lint
        uses: golangci/golangci-lint-action@v2.5.2
